<h2 align = "center">California_Housing Prediction Using XGBOOST</h2>

### Load Data

In [1]:
import pandas as pd
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

In [2]:
housing.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]], shape=(20640, 8))

In [3]:
print(housing.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33:291-297, 1997.

In [4]:
dir(housing)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [5]:
housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [6]:
df = pd.DataFrame(housing.data , columns= housing.feature_names)
df.head(2)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.02381,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.97188,2401.0,2.109842,37.86,-122.22

In [7]:
housing.target_names

['MedHouseVal']

In [8]:
df['MedHouseVal'] = housing.target
df.sample(4)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
13778,2.6875,24.0,5.133858,1.061680,1926.0,2.527559,34.02,-117.06,1.163
17404,1.6875,29.0,3.815041,1.048780,1634.0,3.321138,34.94,-120.44,1.227
6837,3.2344,36.0,4.321492,1.039076,1565.0,2.779751,34.08,-118.12,2.349
1594,8.3678,34.0,7.860304,1.044260,1962.0,2.713693,37.91,-122.12,4.553

In [9]:
df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

In [10]:
df.isnull().sum()

MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

### Train_test_split

In [11]:
from sklearn.model_selection import train_test_split 
X = df.drop("MedHouseVal" , axis = "columns" )
y = df["MedHouseVal"]
x_train , x_test , y_train , y_test = train_test_split(X , y , test_size = 0.3 , random_state = 42)

### Train model using linear regression

In [12]:
from sklearn.linear_model import LinearRegression 
model = LinearRegression()
model.fit(x_train , y_train)
model.score(x_train , y_train)

0.609345972797216

In [13]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error 
import time 
start = time.time()
y_pred = model.predict(x_test)
end_time = time.time()
r2_score = r2_score(y_test , y_pred)
mse = mean_squared_error(y_test , y_pred)
print("r2_score:", r2_score , "mse:", mse , "time: " ,end_time-start)

r2_score: 0.5957702326061665 mse: 0.530567782476675 time:  0.004169464111328125

### Train model using gradient_boosting

In [27]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score, mean_squared_error
model = GradientBoostingRegressor(n_estimators=100)
model.fit(x_train , y_train)
model.score(x_train , y_train)

start = time.time()
y_pred = model.predict(x_test)
end_time = time.time()
r2_score = r2_score(y_test , y_pred)
mse = mean_squared_error(y_test , y_pred)
print( "r2_score:" ,r2_score , "mse:", mse , "time: " ,end_time-start)

r2_score: 0.7803012822391022 mse: 0.28836337869645623 time:  0.016895532608032227

### Train model using XGBOOST

In [25]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_squared_error
import time

model = XGBRegressor()
model.fit(x_train, y_train)

start = time.time()
y_pred_xgb = model.predict(x_test)
end_time = time.time()

r2_score_xgb = r2_score(y_test, y_pred_xgb)
mse_xgb = mean_squared_error(y_test, y_pred_xgb)

print("r2_score_xgb:", r2_score_xgb, "mse:", mse_xgb, "time:", end_time - start)

r2_score_xgb: 0.8386161788339781 mse: 0.21182273803266358 time: 0.01667046546936035

We were used three different model to predict california house price but xgboost is far better than gradient boosting and linear regression