<h2 align="center">Gradient Bossting titanic classification prediction</h2>

### load data

In [13]:
import pandas as pd 
from matplotlib import pyplot as plt 
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [8]:
df = pd.read_csv("titanic.csv")
df.sample(4)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
508,0,3,Mr. James Webber,male,66.0,0,0,8.050
847,0,3,Mr. Johan Svensson,male,74.0,0,0,7.775
819,1,3,Mrs. (Beila) Moor,female,27.0,0,1,12.475
32,1,3,Miss. Mary Agatha Glynn,female,18.0,0,0,7.750

In [9]:
df.shape

(887, 8)

In [11]:
df.isnull().sum()

Survived                   0
Pclass                     0
Name                       0
Sex                        0
Age                        0
Siblings/Spouses Aboard    0
Parents/Children Aboard    0
Fare                       0
dtype: int64

In [16]:
df.tail(4)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.00
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.45
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.00
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.75

### label encoding with sex features

In [18]:
df["Sex"] = df["Sex"].map({"male" : 0 , "female" : 1})

### drop Name column which is not useful in determining the survival rate

In [19]:
df.drop("Name" , axis=1 , inplace=True)

### Train test split

In [22]:
X = df.drop("Survived" , axis=1 )
y = df["Survived"] 

X_train , x_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 10)

### Train model using logistic regression

In [25]:
model = LogisticRegression()
model.fit(X_train , y_train)

LogisticRegression()

### classification report

In [28]:
from sklearn.metrics import classification_report 
y_predict = model.predict(x_test)
report = classification_report( y_test , y_predict)
print(report)

              precision    recall  f1-score   support

           0       0.82      0.88      0.85       112
           1       0.78      0.68      0.73        66

    accuracy                           0.81       178
   macro avg       0.80      0.78      0.79       178
weighted avg       0.81      0.81      0.81       178